/*
  AMANAH ATTENDANCE OPERATIONS UPGRADE
  ------------------------------------
  Adds:
    1) Equipment meter configuration
    2) Attendance meter-in / meter-out fields
    3) Multiple OUT activities
    4) A secure RPC used by the GitHub attendance station

  RUN THIS SCRIPT ONCE IN:
  Supabase Dashboard → SQL Editor

  After running it, reload the GitHub attendance station.
*/


/* ==========================================================
   1. EQUIPMENT METER FIELDS
   ========================================================== */

ALTER TABLE public.equipment
  ADD COLUMN IF NOT EXISTS meter_type text;

ALTER TABLE public.equipment
  ADD COLUMN IF NOT EXISTS current_meter_reading numeric(12,2)
  NOT NULL
  DEFAULT 0;


/*
  Default mapping:
    TRUCK / DUMP / TRACTOR HEAD → ODOMETER
    Everything else             → HOUR METER

  You can later change a specific equipment record manually.
*/

UPDATE public.equipment
SET meter_type =
  CASE
    WHEN upper(coalesce(equipment_type, ''))
         LIKE '%TRUCK%'
      OR upper(coalesce(equipment_type, ''))
         LIKE '%DUMP%'
      OR upper(coalesce(equipment_type, ''))
         LIKE '%TRACTOR HEAD%'
      THEN 'ODOMETER'
    ELSE 'HOUR METER'
  END
WHERE meter_type IS NULL
   OR btrim(meter_type) = '';


DO $$
BEGIN
  ALTER TABLE public.equipment
    ADD CONSTRAINT equipment_meter_type_check
    CHECK (meter_type IN ('ODOMETER', 'HOUR METER'));
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;


/* ==========================================================
   2. ATTENDANCE METER FIELDS
   ========================================================== */

ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS meter_type text;

ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS meter_in numeric(12,2);

ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS meter_out numeric(12,2);

ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS meter_used numeric(12,2);

ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS meter_unit text;


/* ==========================================================
   3. ACTIVITY CHILD TABLE
   ========================================================== */

CREATE TABLE IF NOT EXISTS public.attendance_activities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id text NOT NULL,
  activity_category text NOT NULL,
  activity_description text NOT NULL,
  quantity numeric(12,2) NOT NULL CHECK (quantity > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_attendance_activities_attendance_id
  ON public.attendance_activities(attendance_id);


/*
  The child table is intentionally linked by attendance_id text.
  The attendance table can keep its existing attendance_id data type
  without forcing a type conversion in the migration.
*/


/* ==========================================================
   4. RLS FOR CHILD TABLE
   ========================================================== */

ALTER TABLE public.attendance_activities ENABLE ROW LEVEL SECURITY;


/*
  No public INSERT policy is required.
  The scanner calls the SECURITY DEFINER RPC below.
*/


/* ==========================================================
   5. PREPARE TIME OUT RPC
   ========================================================== */

CREATE OR REPLACE FUNCTION public.prepare_attendance_out(
  p_attendance_id text,
  p_employee_id text,
  p_meter_out numeric,
  p_activities jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$

DECLARE
  rec public.attendance%ROWTYPE;
  v_meter_type text;
  v_meter_unit text;
  v_meter_in numeric;
  v_meter_used numeric;
  v_activity jsonb;
  v_count integer := 0;
BEGIN

  /*
    Lock the active attendance row so two OUT submissions
    cannot modify the same attendance at the same time.
  */

  SELECT *
  INTO rec
  FROM public.attendance
  WHERE attendance_id::text = p_attendance_id
    AND employee_id::text = p_employee_id
    AND upper(coalesce(status, '')) = 'IN'
  FOR UPDATE;


  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'No active attendance was found for this employee.'
    );
  END IF;


  v_meter_type :=
    upper(
      btrim(
        coalesce(
          rec.meter_type,
          'HOUR METER'
        )
      )
    );


  IF v_meter_type NOT IN ('ODOMETER', 'HOUR METER') THEN
    v_meter_type := 'HOUR METER';
  END IF;


  v_meter_unit :=
    CASE
      WHEN v_meter_type = 'ODOMETER'
        THEN 'KM'
      ELSE 'HRS'
    END CASE;


  v_meter_in :=
    rec.meter_in;


  IF v_meter_in IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'This attendance record has no Meter In value. Please close the old attendance record before using the new workflow.'
    );
  END IF;


  IF p_meter_out IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Meter Out is required.'
    );
  END IF;


  IF p_meter_out < v_meter_in THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Meter Out cannot be lower than Meter In.'
    );
  END IF;


  IF jsonb_typeof(coalesce(p_activities, '[]'::jsonb)) <> 'array' THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Activity data must be an array.'
    );
  END IF;


  IF jsonb_array_length(coalesce(p_activities, '[]'::jsonb)) = 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'At least one activity is required.'
    );
  END IF;


  /*
    Validate activities before changing any data.
  */

  FOR v_activity IN
    SELECT value
    FROM jsonb_array_elements(p_activities)
  LOOP

    IF nullif(btrim(v_activity->>'activity_category'), '') IS NULL THEN
      RETURN jsonb_build_object(
        'success', false,
        'error', 'Every activity needs a category.'
      );
    END IF;


    IF nullif(btrim(v_activity->>'activity_description'), '') IS NULL THEN
      RETURN jsonb_build_object(
        'success', false,
        'error', 'Every activity needs a description.'
      );
    END IF;


    IF (v_activity->>'quantity')::numeric <= 0 THEN
      RETURN jsonb_build_object(
        'success', false,
        'error', 'Every activity quantity must be greater than zero.'
      );
    END IF;

  END LOOP;


  v_meter_used :=
    round(
      (p_meter_out - v_meter_in)::numeric,
      2
    );


  /*
    Save the meter information while the attendance is still IN.
    The existing complete_attendance RPC will perform the final
    TIME OUT, total-hours calculation, status change and fuel save.
  */

  UPDATE public.attendance
  SET
    meter_type = v_meter_type,
    meter_out = p_meter_out,
    meter_used = v_meter_used,
    meter_unit = v_meter_unit
  WHERE attendance_id::text = p_attendance_id
    AND employee_id::text = p_employee_id
    AND upper(coalesce(status, '')) = 'IN';


  /*
    Update the equipment master meter without allowing it to move
    backwards.
  */

  IF rec.equipment_id IS NOT NULL THEN

    UPDATE public.equipment
    SET
      meter_type = v_meter_type,
      current_meter_reading =
        GREATEST(
          coalesce(current_meter_reading, 0),
          p_meter_out
        )
    WHERE equipment_id::text =
          rec.equipment_id::text;

  END IF;


  /*
    Replace any previous OUT activity draft for this attendance.
    This makes the RPC safe to retry after a network problem.
  */

  DELETE FROM public.attendance_activities
  WHERE attendance_id = rec.attendance_id::text;


  FOR v_activity IN
    SELECT value
    FROM jsonb_array_elements(p_activities)
  LOOP

    INSERT INTO public.attendance_activities (
      attendance_id,
      activity_category,
      activity_description,
      quantity
    )
    VALUES (
      rec.attendance_id::text,
      btrim(v_activity->>'activity_category'),
      btrim(v_activity->>'activity_description'),
      (v_activity->>'quantity')::numeric
    );

    v_count := v_count + 1;

  END LOOP;


  RETURN jsonb_build_object(
    'success', true,
    'attendance_id', rec.attendance_id::text,
    'meter_type', v_meter_type,
    'meter_unit', v_meter_unit,
    'meter_in', v_meter_in,
    'meter_out', p_meter_out,
    'meter_used', v_meter_used,
    'activity_count', v_count
  );


EXCEPTION
  WHEN others THEN

    RETURN jsonb_build_object(
      'success', false,
      'error', SQLERRM
    );

END;
$function$;


/* ==========================================================
   6. FUNCTION PERMISSIONS
   ========================================================== */

REVOKE ALL
  ON FUNCTION public.prepare_attendance_out(
    text,
    text,
    numeric,
    jsonb
  )
  FROM PUBLIC;

GRANT EXECUTE
  ON FUNCTION public.prepare_attendance_out(
    text,
    text,
    numeric,
    jsonb
  )
  TO anon, authenticated;


/* ==========================================================
   7. USEFUL TABLE PRIVILEGE
   ========================================================== */

/*
  The scanner does not insert directly into
  attendance_activities. The SECURITY DEFINER RPC does it.

  These are read permissions only, useful later for
  authenticated management pages.
*/

GRANT SELECT
  ON public.attendance_activities
  TO authenticated;


/* ==========================================================
   8. OPTIONAL ONE-TIME NORMALIZATION
   ========================================================== */

/*
  Fill meter_unit for any existing attendance rows that already
  have meter_type but no meter_unit.
*/

UPDATE public.attendance
SET meter_unit =
  CASE
    WHEN upper(coalesce(meter_type, '')) = 'ODOMETER'
      THEN 'KM'
    ELSE 'HRS'
  END
WHERE meter_unit IS NULL
  AND meter_type IS NOT NULL;
